# SPDX-License-Identifier: Apache-2.0
# HIL snippet configuration: exactly these four symbols (docs/HIL.md 8.3 and Appendix A, FW-15).
# CONFIG_HIL comes from the lib/hil module (-DZEPHYR_EXTRA_MODULES=$HIL/lib/hil);
# CONFIG_HIL_SHELL defaults to y there.
CONFIG_HIL=y
CONFIG_SHELL=y
CONFIG_HWINFO=y
CONFIG_REBOOT=y
