# SPDX-License-Identifier: Apache-2.0
"""BACnet enumerations: object types, properties, engineering units, errors.

The name tables use the text names of the BACnet stack used by the firmware
(``bactext.c`` of bacnet-stack 54544d02e427), so names returned by the
node (``uc_node objects``, ``uc_io catalog``) and names accepted by it match
the ones here. ``PROPERTIES`` includes the stack's two mixed-case names
(``number-of-APDU-retries``, ``COV-period``); lookups are case-insensitive
and accept ``_`` or spaces in place of ``-``.

The tables from ``OBJECT_TYPES`` to ``UNCONFIRMED_SERVICES`` were generated
by dumping the ``INDTEXT_DATA`` tables of bactext.c; the service names were
converted to lower-case hyphenated form (``ReadProperty`` ->
``read-property``) and the ``error-code-`` prefix of one error code name was
dropped. Reject/abort reasons, constants and helpers are hand-written.
"""

from __future__ import annotations

# BACnetObjectType (clause 21), standard types
OBJECT_TYPES: dict[str, int] = {
    "analog-input": 0,
    "analog-output": 1,
    "analog-value": 2,
    "binary-input": 3,
    "binary-output": 4,
    "binary-value": 5,
    "calendar": 6,
    "command": 7,
    "device": 8,
    "event-enrollment": 9,
    "file": 10,
    "group": 11,
    "loop": 12,
    "multi-state-input": 13,
    "multi-state-output": 14,
    "notification-class": 15,
    "program": 16,
    "schedule": 17,
    "averaging": 18,
    "multi-state-value": 19,
    "trend-log": 20,
    "life-safety-point": 21,
    "life-safety-zone": 22,
    "accumulator": 23,
    "pulse-converter": 24,
    "event-log": 25,
    "global-group": 26,
    "trend-log-multiple": 27,
    "load-control": 28,
    "structured-view": 29,
    "access-door": 30,
    "timer": 31,
    "access-credential": 32,
    "access-point": 33,
    "access-rights": 34,
    "access-user": 35,
    "access-zone": 36,
    "credential-data-input": 37,
    "network-security": 38,
    "bitstring-value": 39,
    "characterstring-value": 40,
    "date-pattern-value": 41,
    "date-value": 42,
    "datetime-pattern-value": 43,
    "datetime-value": 44,
    "integer-value": 45,
    "large-analog-value": 46,
    "octetstring-value": 47,
    "positive-integer-value": 48,
    "time-pattern-value": 49,
    "time-value": 50,
    "notification-forwarder": 51,
    "alert-enrollment": 52,
    "channel": 53,
    "lighting-output": 54,
    "binary-lighting-output": 55,
    "network-port": 56,
    "elevator-group": 57,
    "escalator": 58,
    "lift": 59,
    "staging": 60,
    "audit-log": 61,
    "audit-reporter": 62,
    "color": 63,
    "color-temperature": 64,
}


# BACnetPropertyIdentifier
PROPERTIES: dict[str, int] = {
    "acked-transitions": 0,
    "ack-required": 1,
    "action": 2,
    "action-text": 3,
    "active-text": 4,
    "active-vt-sessions": 5,
    "alarm-value": 6,
    "alarm-values": 7,
    "all": 8,
    "all-writes-successful": 9,
    "apdu-segment-timeout": 10,
    "apdu-timeout": 11,
    "application-software-version": 12,
    "archive": 13,
    "bias": 14,
    "change-of-state-count": 15,
    "change-of-state-time": 16,
    "notification-class": 17,
    "controlled-variable-reference": 19,
    "controlled-variable-units": 20,
    "controlled-variable-value": 21,
    "cov-increment": 22,
    "date-list": 23,
    "daylight-savings-status": 24,
    "deadband": 25,
    "derivative-constant": 26,
    "derivative-constant-units": 27,
    "description": 28,
    "description-of-halt": 29,
    "device-address-binding": 30,
    "device-type": 31,
    "effective-period": 32,
    "elapsed-active-time": 33,
    "error-limit": 34,
    "event-enable": 35,
    "event-state": 36,
    "event-type": 37,
    "exception-schedule": 38,
    "fault-values": 39,
    "feedback-value": 40,
    "file-access-method": 41,
    "file-size": 42,
    "file-type": 43,
    "firmware-revision": 44,
    "high-limit": 45,
    "inactive-text": 46,
    "in-process": 47,
    "instance-of": 48,
    "integral-constant": 49,
    "integral-constant-units": 50,
    "issue-confirmednotifications": 51,
    "limit-enable": 52,
    "list-of-group-members": 53,
    "list-of-object-property-references": 54,
    "list-of-session-keys": 55,
    "local-date": 56,
    "local-time": 57,
    "location": 58,
    "low-limit": 59,
    "manipulated-variable-reference": 60,
    "maximum-output": 61,
    "max-apdu-length-accepted": 62,
    "max-info-frames": 63,
    "max-master": 64,
    "max-pres-value": 65,
    "minimum-off-time": 66,
    "minimum-on-time": 67,
    "minimum-output": 68,
    "min-pres-value": 69,
    "model-name": 70,
    "modification-date": 71,
    "notify-type": 72,
    "number-of-APDU-retries": 73,
    "number-of-states": 74,
    "object-identifier": 75,
    "object-list": 76,
    "object-name": 77,
    "object-property-reference": 78,
    "object-type": 79,
    "optional": 80,
    "out-of-service": 81,
    "output-units": 82,
    "event-parameters": 83,
    "polarity": 84,
    "present-value": 85,
    "priority": 86,
    "priority-array": 87,
    "priority-for-writing": 88,
    "process-identifier": 89,
    "program-change": 90,
    "program-location": 91,
    "program-state": 92,
    "proportional-constant": 93,
    "proportional-constant-units": 94,
    "protocol-conformance-class": 95,
    "protocol-object-types-supported": 96,
    "protocol-services-supported": 97,
    "protocol-version": 98,
    "read-only": 99,
    "reason-for-halt": 100,
    "recipient": 101,
    "recipient-list": 102,
    "reliability": 103,
    "relinquish-default": 104,
    "required": 105,
    "resolution": 106,
    "segmentation-supported": 107,
    "setpoint": 108,
    "setpoint-reference": 109,
    "state-text": 110,
    "status-flags": 111,
    "system-status": 112,
    "time-delay": 113,
    "time-of-active-time-reset": 114,
    "time-of-state-count-reset": 115,
    "time-synchronization-recipients": 116,
    "units": 117,
    "update-interval": 118,
    "utc-offset": 119,
    "vendor-identifier": 120,
    "vendor-name": 121,
    "vt-classes-supported": 122,
    "weekly-schedule": 123,
    "attempted-samples": 124,
    "average-value": 125,
    "buffer-size": 126,
    "client-cov-increment": 127,
    "cov-resubscription-interval": 128,
    "current-notify-time": 129,
    "event-time-stamps": 130,
    "log-buffer": 131,
    "log-device-object-property": 132,
    "enable": 133,
    "log-interval": 134,
    "maximum-value": 135,
    "minimum-value": 136,
    "notification-threshold": 137,
    "previous-notify-time": 138,
    "protocol-revision": 139,
    "records-since-notification": 140,
    "record-count": 141,
    "start-time": 142,
    "stop-time": 143,
    "stop-when-full": 144,
    "total-record-count": 145,
    "valid-samples": 146,
    "window-interval": 147,
    "window-samples": 148,
    "maximum-value-timestamp": 149,
    "minimum-value-timestamp": 150,
    "variance-value": 151,
    "active-cov-subscriptions": 152,
    "backup-failure-timeout": 153,
    "configuration-files": 154,
    "database-revision": 155,
    "direct-reading": 156,
    "last-restore-time": 157,
    "maintenance-required": 158,
    "member-of": 159,
    "mode": 160,
    "operation-expected": 161,
    "setting": 162,
    "silenced": 163,
    "tracking-value": 164,
    "zone-members": 165,
    "life-safety-alarm-values": 166,
    "max-segments-accepted": 167,
    "profile-name": 168,
    "auto-slave-discovery": 169,
    "manual-slave-address-binding": 170,
    "slave-address-binding": 171,
    "slave-proxy-enable": 172,
    "last-notify-record": 173,
    "schedule-default": 174,
    "accepted-modes": 175,
    "adjust-value": 176,
    "count": 177,
    "count-before-change": 178,
    "count-change-time": 179,
    "COV-period": 180,
    "input-reference": 181,
    "limit-monitoring-interval": 182,
    "logging-object": 183,
    "logging-record": 184,
    "prescale": 185,
    "pulse-rate": 186,
    "scale": 187,
    "scale-factor": 188,
    "update-time": 189,
    "value-before-change": 190,
    "value-set": 191,
    "value-change-time": 192,
    "align-intervals": 193,
    "interval-offset": 195,
    "last-restart-reason": 196,
    "logging-type": 197,
    "restart-notification-recipients": 202,
    "time-of-device-restart": 203,
    "time-synchronization-interval": 204,
    "trigger": 205,
    "utc-time-synchronization-recipients": 206,
    "node-subtype": 207,
    "node-type": 208,
    "structured-object-list": 209,
    "subordinate-annotations": 210,
    "subordinate-list": 211,
    "actual-shed-level": 212,
    "duty-window": 213,
    "expected-shed-level": 214,
    "full-duty-baseline": 215,
    "requested-shed-level": 218,
    "shed-duration": 219,
    "shed-level-descriptions": 220,
    "shed-levels": 221,
    "state-description": 222,
    "door-alarm-state": 226,
    "door-extended-pulse-time": 227,
    "door-members": 228,
    "door-open-too-long-time": 229,
    "door-pulse-time": 230,
    "door-status": 231,
    "door-unlock-delay-time": 232,
    "lock-status": 233,
    "masked-alarm-values": 234,
    "secured-status": 235,
    "absentee-limit": 244,
    "access-alarm-events": 245,
    "access-doors": 246,
    "access-event": 247,
    "access-event-authentication-factor": 248,
    "access-event-credential": 249,
    "access-event-time": 250,
    "access-transaction-events": 251,
    "accompaniment": 252,
    "accompaniment-time": 253,
    "activation-time": 254,
    "active-authentication-policy": 255,
    "assigned-access-rights": 256,
    "authentication-factors": 257,
    "authentication-policy-list": 258,
    "authentication-policy-names": 259,
    "authentication-status": 260,
    "authorization-mode": 261,
    "belongs-to": 262,
    "credential-disable": 263,
    "credential-status": 264,
    "credentials": 265,
    "credentials-in-zone": 266,
    "days-remaining": 267,
    "entry-points": 268,
    "exit-points": 269,
    "expiration-time": 270,
    "extended-time-enable": 271,
    "failed-attempt-events": 272,
    "failed-attempts": 273,
    "failed-attempts-time": 274,
    "last-access-event": 275,
    "last-access-point": 276,
    "last-credential-added": 277,
    "last-credential-added-time": 278,
    "last-credential-removed": 279,
    "last-credential-removed-time": 280,
    "last-use-time": 281,
    "lockout": 282,
    "lockout-relinquish-time": 283,
    "master-exemption": 284,
    "max-failed-attempts": 285,
    "members": 286,
    "muster-point": 287,
    "negative-access-rules": 288,
    "number-of-authentication-policies": 289,
    "occupancy-count": 290,
    "occupancy-count-adjust": 291,
    "occupancy-count-enable": 292,
    "occupancy-exemption": 293,
    "occupancy-lower-limit": 294,
    "occupancy-lower-limit-enforced": 295,
    "occupancy-state": 296,
    "occupancy-upper-limit": 297,
    "occupancy-upper-limit-enforced": 298,
    "passback-exemption": 299,
    "passback-mode": 300,
    "passback-timeout": 301,
    "positive-access-rules": 302,
    "reason-for-disable": 303,
    "supported-formats": 304,
    "supported-format-classes": 305,
    "threat-authority": 306,
    "threat-level": 307,
    "trace-flag": 308,
    "transaction-notification-class": 309,
    "user-external-identifier": 310,
    "user-information-reference": 311,
    "user-name": 317,
    "user-type": 318,
    "uses-remaining": 319,
    "zone-from": 320,
    "zone-to": 321,
    "access-event-tag": 322,
    "global-identifier": 323,
    "verification-time": 326,
    "base-device-security-policy": 327,
    "distribution-key-revision": 328,
    "do-not-hide": 329,
    "key-sets": 330,
    "last-key-server": 331,
    "network-access-security-policies": 332,
    "packet-reorder-time": 333,
    "security-pdu-timeout": 334,
    "security-time-window": 335,
    "supported-security-algorithm": 336,
    "update-key-set-timeout": 337,
    "backup-and-restore-state": 338,
    "backup-preparation-time": 339,
    "restore-completion-time": 340,
    "restore-preparation-time": 341,
    "bit-mask": 342,
    "bit-text": 343,
    "is-utc": 344,
    "group-members": 345,
    "group-member-names": 346,
    "member-status-flags": 347,
    "requested-update-interval": 348,
    "covu-period": 349,
    "covu-recipients": 350,
    "event-message-texts": 351,
    "event-message-texts-config": 352,
    "event-detection-enable": 353,
    "event-algorithm-inhibit": 354,
    "event-algorithm-inhibit-ref": 355,
    "time-delay-normal": 356,
    "reliability-evaluation-inhibit": 357,
    "fault-parameters": 358,
    "fault-type": 359,
    "local-forwarding-only": 360,
    "process-identifier-filter": 361,
    "subscribed-recipients": 362,
    "port-filter": 363,
    "authorization-exemptions": 364,
    "allow-group-delay-inhibit": 365,
    "channel-number": 366,
    "control-groups": 367,
    "execution-delay": 368,
    "last-priority": 369,
    "write-status": 370,
    "property-list": 371,
    "serial-number": 372,
    "blink-warn-enable": 373,
    "default-fade-time": 374,
    "default-ramp-rate": 375,
    "default-step-increment": 376,
    "egress-time": 377,
    "in-progress": 378,
    "instantaneous-power": 379,
    "lighting-command": 380,
    "lighting-command-default-priority": 381,
    "max-actual-value": 382,
    "min-actual-value": 383,
    "power": 384,
    "transition": 385,
    "egress-active": 386,
    "interface-value": 387,
    "fault-high-limit": 388,
    "fault-low-limit": 389,
    "low-diff-limit": 390,
    "strike-count": 391,
    "time-of-strike-count-reset": 392,
    "default-timeout": 393,
    "initial-timeout": 394,
    "last-state-change": 395,
    "state-change-values": 396,
    "timer-running": 397,
    "timer-state": 398,
    "apdu-length": 399,
    "ip-address": 400,
    "ip-default-gateway": 401,
    "ip-dhcp-enable": 402,
    "ip-dhcp-lease-time": 403,
    "ip-dhcp-lease-time-remaining": 404,
    "ip-dhcp-server": 405,
    "ip-dns-server": 406,
    "bacnet-ip-global-address": 407,
    "bacnet-ip-mode": 408,
    "bacnet-ip-multicast-address": 409,
    "bacnet-ip-nat-traversal": 410,
    "ip-subnet-mask": 411,
    "bacnet-ip-udp-port": 412,
    "bbmd-accept-fd-registrations": 413,
    "bbmd-broadcast-distribution-table": 414,
    "bbmd-foreign-device-table": 415,
    "changes-pending": 416,
    "command": 417,
    "fd-bbmd-address": 418,
    "fd-subscription-lifetime": 419,
    "link-speed": 420,
    "link-speeds": 421,
    "link-speed-autonegotiate": 422,
    "mac-address": 423,
    "network-interface-name": 424,
    "network-number": 425,
    "network-number-quality": 426,
    "network-type": 427,
    "routing-table": 428,
    "virtual-mac-address-table": 429,
    "command-time-array": 430,
    "current-command-priority": 431,
    "last-command-time": 432,
    "value-source": 433,
    "value-source-array": 434,
    "bacnet-ipv6-mode": 435,
    "ipv6-address": 436,
    "ipv6-prefix-length": 437,
    "bacnet-ipv6-udp-port": 438,
    "ipv6-default-gateway": 439,
    "bacnet-ipv6-multicast-address": 440,
    "ipv6-dns-server": 441,
    "ipv6-auto-addressing-enable": 442,
    "ipv6-dhcp-lease-time": 443,
    "ipv6-dhcp-lease-time-remaining": 444,
    "ipv6-dhcp-server": 445,
    "ipv6-zone-index": 446,
    "assigned-landing-calls": 447,
    "car-assigned-direction": 448,
    "car-door-command": 449,
    "car-door-status": 450,
    "car-door-text": 451,
    "car-door-zone": 452,
    "car-drive-status": 453,
    "car-load": 454,
    "car-load-units": 455,
    "car-mode": 456,
    "car-moving-direction": 457,
    "car-position": 458,
    "elevator-group": 459,
    "energy-meter": 460,
    "energy-meter-ref": 461,
    "escalator-mode": 462,
    "fault-signals": 463,
    "floor-text": 464,
    "group-id": 465,
    "group-mode": 467,
    "higher-deck": 468,
    "installation-id": 469,
    "landing-calls": 470,
    "landing-call-control": 471,
    "landing-door-status": 472,
    "lower-deck": 473,
    "machine-room-id": 474,
    "making-car-call": 475,
    "next-stopping-floor": 476,
    "operation-direction": 477,
    "passenger-alarm": 478,
    "power-mode": 479,
    "registered-car-call": 480,
    "active-cov-multiple-subscriptions": 481,
    "protocol-level": 482,
    "reference-port": 483,
    "deployed-profile-location": 484,
    "profile-location": 485,
    "tags": 486,
    "subordinate-node-types": 487,
    "subordinate-tags": 488,
    "subordinate-relationships": 489,
    "default-subordinate-relationship": 490,
    "represents": 491,
    "default-present-value": 492,
    "present-stage": 493,
    "stages": 494,
    "stage-names": 495,
    "target-references": 496,
    "audit-source-level": 497,
    "audit-level": 498,
    "audit-notification-recipient": 499,
    "audit-priority-filter": 500,
    "auditable-operations": 501,
    "delete-on-forward": 502,
    "maximum-send-delay": 503,
    "monitored-objects": 504,
    "send-now": 505,
    "floor-number": 506,
    "device-uuid": 507,
    "additional-reference-ports": 508,
    "certificate-signing-request-file": 509,
    "command-validation-result": 510,
    "issuer-certificate-files": 511,
    "max-bvlc-length-accepted": 4194304,
    "max-npdu-length-accepted": 4194305,
    "operational-certificate-file": 4194306,
    "current-health": 4194307,
    "sc-connect-wait-timeout": 4194308,
    "sc-direct-connect-accept-enable": 4194309,
    "sc-direct-connect-accept-uris": 4194310,
    "sc-direct-connect-binding": 4194311,
    "sc-direct-connect-connection-status": 4194312,
    "sc-direct-connect-initiate-enable": 4194313,
    "sc-disconnect-wait-timeout": 4194314,
    "sc-failed-connection-requests": 4194315,
    "sc-failover-hub-connection-status": 4194316,
    "sc-failover-hub-uri": 4194317,
    "sc-hub-connector-state": 4194318,
    "sc-hub-function-accept-uris": 4194319,
    "sc-hub-function-binding": 4194320,
    "sc-hub-function-connection-status": 4194321,
    "sc-hub-function-enable": 4194322,
    "sc-heartbeat-timeout": 4194323,
    "sc-primary-hub-connection-status": 4194324,
    "sc-primary-hub-uri": 4194325,
    "sc-maximum-reconnect-time": 4194326,
    "sc-minimum-reconnect-time": 4194327,
    "color-override": 4194328,
    "color-reference": 4194329,
    "default-color": 4194330,
    "default-color-temperature": 4194331,
    "override-color-reference": 4194332,
    "write-every-scheduled-action": 4194333,
    "color-command": 4194334,
    "high-end-trim": 4194335,
    "low-end-trim": 4194336,
    "trim-fade-time": 4194337,
    "device-address-proxy-enable": 4194338,
    "device-address-proxy-table": 4194339,
    "device-address-proxy-timeout": 4194340,
    "default-on-value": 4194341,
    "last-on-value": 4194342,
    "authorization-cache": 4194343,
    "authorization-groups": 4194344,
    "authorization-policy": 4194345,
    "authorization-scope": 4194346,
    "authorization-server": 4194347,
    "authorization-status": 4194348,
    "max-proxied-i-ams-per-second": 4194349,
}


# BACnetEngineeringUnits
UNITS: dict[str, int] = {
    "square-meters": 0,
    "square-feet": 1,
    "milliamperes": 2,
    "amperes": 3,
    "ohms": 4,
    "volts": 5,
    "kilovolts": 6,
    "megavolts": 7,
    "volt-amperes": 8,
    "kilovolt-amperes": 9,
    "megavolt-amperes": 10,
    "volt-amperes-reactive": 11,
    "kilovolt-amperes-reactive": 12,
    "megavolt-amperes-reactive": 13,
    "degrees-phase": 14,
    "power-factor": 15,
    "joules": 16,
    "kilojoules": 17,
    "watt-hours": 18,
    "kilowatt-hours": 19,
    "btus": 20,
    "therms": 21,
    "ton-hours": 22,
    "joules-per-kilogram-dry-air": 23,
    "btus-per-pound-dry-air": 24,
    "cycles-per-hour": 25,
    "cycles-per-minute": 26,
    "hertz": 27,
    "grams-of-water-per-kilogram-dry-air": 28,
    "percent-relative-humidity": 29,
    "millimeters": 30,
    "meters": 31,
    "inches": 32,
    "feet": 33,
    "watts-per-square-foot": 34,
    "watts-per-square-meter": 35,
    "lumens": 36,
    "luxes": 37,
    "foot-candles": 38,
    "kilograms": 39,
    "pounds-mass": 40,
    "tons": 41,
    "kilograms-per-second": 42,
    "kilograms-per-minute": 43,
    "kilograms-per-hour": 44,
    "pounds-mass-per-minute": 45,
    "pounds-mass-per-hour": 46,
    "watts": 47,
    "kilowatts": 48,
    "megawatts": 49,
    "btus-per-hour": 50,
    "horsepower": 51,
    "tons-refrigeration": 52,
    "pascals": 53,
    "kilopascals": 54,
    "bars": 55,
    "pounds-force-per-square-inch": 56,
    "centimeters-of-water": 57,
    "inches-of-water": 58,
    "millimeters-of-mercury": 59,
    "centimeters-of-mercury": 60,
    "inches-of-mercury": 61,
    "degrees-celsius": 62,
    "kelvin": 63,
    "degrees-fahrenheit": 64,
    "degree-days-celsius": 65,
    "degree-days-fahrenheit": 66,
    "years": 67,
    "months": 68,
    "weeks": 69,
    "days": 70,
    "hours": 71,
    "minutes": 72,
    "seconds": 73,
    "meters-per-second": 74,
    "kilometers-per-hour": 75,
    "feet-per-second": 76,
    "feet-per-minute": 77,
    "miles-per-hour": 78,
    "cubic-feet": 79,
    "cubic-meters": 80,
    "imperial-gallons": 81,
    "liters": 82,
    "us-gallons": 83,
    "cubic-feet-per-minute": 84,
    "cubic-meters-per-second": 85,
    "imperial-gallons-per-minute": 86,
    "liters-per-second": 87,
    "liters-per-minute": 88,
    "us-gallons-per-minute": 89,
    "degrees-angular": 90,
    "degrees-celsius-per-hour": 91,
    "degrees-celsius-per-minute": 92,
    "degrees-fahrenheit-per-hour": 93,
    "degrees-fahrenheit-per-minute": 94,
    "no-units": 95,
    "parts-per-million": 96,
    "parts-per-billion": 97,
    "percent": 98,
    "percent-per-second": 99,
    "per-minute": 100,
    "per-second": 101,
    "psi-per-degree-fahrenheit": 102,
    "radians": 103,
    "revolutions-per-minute": 104,
    "currency1": 105,
    "currency2": 106,
    "currency3": 107,
    "currency4": 108,
    "currency5": 109,
    "currency6": 110,
    "currency7": 111,
    "currency8": 112,
    "currency9": 113,
    "currency10": 114,
    "square-inches": 115,
    "square-centimeters": 116,
    "btus-per-pound": 117,
    "centimeters": 118,
    "pounds-mass-per-second": 119,
    "delta-degrees-fahrenheit": 120,
    "delta-kelvin": 121,
    "kilohms": 122,
    "megohms": 123,
    "millivolts": 124,
    "kilojoules-per-kilogram": 125,
    "megajoules": 126,
    "joules-per-degree-kelvin": 127,
    "joules-per-kilogram-degree-kelvin": 128,
    "kilohertz": 129,
    "megahertz": 130,
    "per-hour": 131,
    "milliwatts": 132,
    "hectopascals": 133,
    "millibars": 134,
    "cubic-meters-per-hour": 135,
    "liters-per-hour": 136,
    "kilowatt-hours-per-square-meter": 137,
    "kilowatt-hours-per-square-foot": 138,
    "megajoules-per-square-meter": 139,
    "megajoules-per-square-foot": 140,
    "watts-per-square-meter-degree-kelvin": 141,
    "cubic-feet-per-second": 142,
    "percent-obscuration-per-foot": 143,
    "percent-obscuration-per-meter": 144,
    "milliohms": 145,
    "megawatt-hours": 146,
    "kilo-btus": 147,
    "mega-btus": 148,
    "kilojoules-per-kilogram-dry-air": 149,
    "megajoules-per-kilogram-dry-air": 150,
    "kilojoules-per-degree-kelvin": 151,
    "megajoules-per-degree-kelvin": 152,
    "newton": 153,
    "grams-per-second": 154,
    "grams-per-minute": 155,
    "tons-per-hour": 156,
    "kilo-btus-per-hour": 157,
    "hundredths-seconds": 158,
    "milliseconds": 159,
    "newton-meters": 160,
    "millimeters-per-second": 161,
    "millimeters-per-minute": 162,
    "meters-per-minute": 163,
    "meters-per-hour": 164,
    "cubic-meters-per-minute": 165,
    "meters-per-second-per-second": 166,
    "amperes-per-meter": 167,
    "amperes-per-square-meter": 168,
    "ampere-square-meters": 169,
    "farads": 170,
    "henrys": 171,
    "ohm-meters": 172,
    "siemens": 173,
    "siemens-per-meter": 174,
    "teslas": 175,
    "volts-per-degree-kelvin": 176,
    "volts-per-meter": 177,
    "webers": 178,
    "candelas": 179,
    "candelas-per-square-meter": 180,
    "kelvin-per-hour": 181,
    "kelvin-per-minute": 182,
    "joule-seconds": 183,
    "radians-per-second": 184,
    "square-meters-per-newton": 185,
    "kilograms-per-cubic-meter": 186,
    "newton-seconds": 187,
    "newtons-per-meter": 188,
    "watts-per-meter-per-degree-kelvin": 189,
    "micro-siemens": 190,
    "cubic-feet-per-hour": 191,
    "us-gallons-per-hour": 192,
    "kilometers": 193,
    "micrometers": 194,
    "grams": 195,
    "milligrams": 196,
    "milliliters": 197,
    "milliliters-per-second": 198,
    "decibels": 199,
    "decibels-millivolt": 200,
    "decibels-volt": 201,
    "millisiemens": 202,
    "watt-reactive-hours": 203,
    "kilowatt-reactive-hours": 204,
    "megawatt-reactive-hours": 205,
    "millimeters-of-water": 206,
    "per-mille": 207,
    "grams-per-gram": 208,
    "kilograms-per-kilogram": 209,
    "grams-per-kilogram": 210,
    "milligrams-per-gram": 211,
    "milligrams-per-kilogram": 212,
    "grams-per-milliliter": 213,
    "grams-per-liter": 214,
    "milligrams-per-liter": 215,
    "micrograms-per-liter": 216,
    "grams-per-cubic-meter": 217,
    "milligrams-per-cubic-meter": 218,
    "micrograms-per-cubic-meter": 219,
    "nanograms-per-cubic-meter": 220,
    "grams-per-cubic-centimeter": 221,
    "becquerels": 222,
    "kilobecquerels": 223,
    "megabecquerels": 224,
    "gray": 225,
    "milligray": 226,
    "microgray": 227,
    "sieverts": 228,
    "millisieverts": 229,
    "microsieverts": 230,
    "microsieverts-per-hour": 231,
    "decibels-a": 232,
    "nephelometric-turbidity-unit": 233,
    "pH": 234,
    "grams-per-square-meter": 235,
    "minutes-per-degree-kelvin": 236,
    "ohm-meter-squared-per-meter": 237,
    "ampere-seconds": 238,
    "volt-ampere-hours": 239,
    "kilovolt-ampere-hours": 240,
    "megavolt-ampere-hours": 241,
    "volt-ampere-reactive-hours": 242,
    "kilovolt-ampere-reactive-hours": 243,
    "megavolt-ampere-reactive-hours": 244,
    "volt-square-hours": 245,
    "ampere-square-hours": 246,
    "joule-per-hours": 247,
    "cubic-feet-per-day": 248,
    "cubic-meters-per-day": 249,
    "watt-hours-per-cubic-meter": 250,
    "joules-per-cubic-meter": 251,
    "mole-percent": 252,
    "pascal-seconds": 253,
    "million-standard-cubic-feet-per-minute": 254,
    "standard-cubic-feet-per-day": 47808,
    "million-standard-cubic-feet-per-day": 47809,
    "thousand-cubic-feet-per-day": 47810,
    "thousand-standard-cubic-feet-per-day": 47811,
    "pounds-mass-per-day": 47812,
    "millirems": 47814,
    "millirems-per-hour": 47815,
    "degrees-lovibond": 47816,
    "alcohol-by-volume": 47817,
    "international-bittering-units": 47818,
    "european-bitterness-units": 47819,
    "degrees-plato": 47820,
    "specific-gravity": 47821,
    "european-brewing-convention": 47822,
    "per-day": 47823,
    "per-millisecond": 47824,
    "yards": 47825,
    "miles": 47826,
    "nautical-miles": 47827,
    "nanograms": 47828,
    "micrograms": 47829,
    "metric-tonnes": 47830,
    "short-tons": 47831,
    "long-tons": 47832,
    "grams-per-hour": 47833,
    "grams-per-day": 47834,
    "kilograms-per-day": 47835,
    "short-tons-per-second": 47836,
    "short-tons-per-minute": 47837,
    "short-tons-per-hour": 47838,
    "short-tons-per-day": 47839,
    "metric-tonnes-per-second": 47840,
    "metric-tonnes-per-minute": 47841,
    "metric-tonnes-per-hour": 47842,
    "metric-tonnes-per-day": 47843,
    "long-tons-per-second": 47844,
    "long-tons-per-minute": 47845,
    "long-tons-per-hour": 47846,
    "long-tons-per-day": 47847,
    "btus-per-second": 47848,
    "btus-per-minute": 47849,
    "btus-per-day": 47850,
    "kilo-btus-per-second": 47851,
    "kilo-btus-per-minute": 47852,
    "kilo-btus-per-day": 47853,
    "mega-btus-per-second": 47854,
    "mega-btus-per-minute": 47855,
    "mega-btus-per-hour": 47856,
    "mega-btus-per-day": 47857,
    "joules-per-second": 47858,
    "joules-per-minute": 47859,
    "joules-per-day": 47860,
    "kilojoules-per-second": 47861,
    "kilojoules-per-minute": 47862,
    "kilojoules-per-hour": 47863,
    "kilojoules-per-day": 47864,
    "megajoules-per-second": 47865,
    "megajoules-per-minute": 47866,
    "megajoules-per-hour": 47867,
    "megajoules-per-day": 47868,
    "degrees-celsius-per-day": 47869,
    "kelvin-per-day": 47870,
    "degrees-fahrenheit-per-day": 47871,
    "delta-degrees-celsius": 47872,
    "million-cubic-feet-per-minute": 47873,
    "million-cubic-feet-per-day": 47874,
    "imperial-gallons-per-second": 47875,
    "imperial-gallons-per-hour": 47876,
    "imperial-gallons-per-day": 47877,
    "liters-per-day": 47878,
    "us-gallons-per-second": 47879,
    "us-gallons-per-day": 47880,
    "percent-per-minute": 47881,
    "percent-per-hour": 47882,
    "percent-per-day": 47883,
    "per-million": 47884,
    "per-billion": 47885,
    "micrograms-per-gram": 47886,
    "nanograms-per-gram": 47887,
    "micrograms-per-kilogram": 47888,
    "nanograms-per-kilogram": 47889,
    "milligrams-per-milliliter": 47890,
    "micrograms-per-milliliter": 47891,
    "nanograms-per-milliliter": 47892,
    "kilograms-per-liter": 47893,
    "nanograms-per-liter": 47894,
    "milligrams-per-cubic-centimeter": 47895,
    "micrograms-per-cubic-centimeter": 47896,
    "nanograms-per-cubic-centimeter": 47897,
    "btu-per-hour-per-watt": 47898,
    "btu-per-watt-hour-seasonal": 47899,
    "coefficient-of-performance": 47900,
    "coefficient-of-performance-seasonal": 47901,
    "kilowatt-per-ton-refrigeration": 47902,
    "lumens-per-watt": 47903,
    "pound-force-feet": 47904,
    "pound-force-inches": 47905,
    "ounce-force-inches": 47906,
    "pounds-force-per-square-inch-absolute": 47907,
    "pounds-force-per-square-inch-gauge": 47908,
    "microsiemens-per-centimeter": 47909,
    "millisiemens-per-centimeter": 47910,
    "millisiemens-per-meter": 47911,
    "millions-of-us-gallons": 47912,
    "millions-of-imperial-gallons": 47913,
    "milliliters-per-minute": 47914,
    "mils-per-year": 47915,
    "millimeters-per-year": 47916,
    "pulses-per-minute": 47917,
    "active-energy-pulse-value": 47918,
    "reactive-energy-pulse-value": 47919,
    "apparent-energy-pulse-value": 47920,
    "volt-squared-hour-pulse-value": 47921,
    "ampere-squared-hour-pulse-value": 47922,
    "cubic-meter-pulse-value": 47923,
    "gigawatts": 47924,
    "gigajoules": 47925,
    "terajoules": 47926,
    "gigawatt-hours": 47927,
    "gigawatt-reactive-hours": 47928,
    "bits-per-second": 47929,
    "kilobits-per-second": 47930,
    "megabits-per-second": 47931,
    "gigabits-per-second": 47932,
    "bytes-per-second": 47933,
    "kilobytes-per-second": 47934,
    "megabytes-per-second": 47935,
    "gigabytes-per-second": 47936,
    "volume1": 47937,
    "volume2": 47938,
    "volume3": 47939,
    "volume4": 47940,
    "volume5": 47941,
    "volume6": 47942,
    "volume7": 47943,
    "volume8": 47944,
    "volume9": 47945,
    "volume10": 47946,
    "volumetric-flow1": 47947,
    "volumetric-flow2": 47948,
    "volumetric-flow3": 47949,
    "volumetric-flow4": 47950,
    "volumetric-flow5": 47951,
    "volumetric-flow6": 47952,
    "volumetric-flow7": 47953,
    "volumetric-flow8": 47954,
    "volumetric-flow9": 47955,
    "volumetric-flow10": 47956,
    "site-unit1": 47958,
    "site-unit2": 47959,
    "site-unit3": 47960,
    "site-unit4": 47961,
    "site-unit5": 47962,
    "site-unit6": 47963,
    "site-unit7": 47964,
    "site-unit8": 47965,
    "site-unit9": 47966,
    "site-unit10": 47967,
    "particles-per-cubic-foot": 47968,
    "particles-per-cubic-meter": 47969,
    "picocuries-per-liter": 47970,
    "becquerels-per-cubic-meter": 47971,
    "grains-of-water-per-pound-dry-air": 47972,
    "degree-hours-celsius": 47973,
    "degree-hours-fahrenheit": 47974,
    "degree-minutes-celsius": 47975,
    "degree-minutes-fahrenheit": 47976,
    "degree-seconds-celsius": 47977,
    "degree-seconds-fahrenheit": 47978,
    "microseconds": 47979,
    "nanoseconds": 47980,
    "picoseconds": 47981,
}


# Error class
ERROR_CLASSES: dict[str, int] = {
    "device": 0,
    "object": 1,
    "property": 2,
    "resources": 3,
    "security": 4,
    "services": 5,
    "vt": 6,
    "communication": 7,
}


# Error code
ERROR_CODES: dict[str, int] = {
    "other": 0,
    "authentication-failed": 1,
    "configuration-in-progress": 2,
    "device-busy": 3,
    "dynamic-creation-not-supported": 4,
    "file-access-denied": 5,
    "incompatible-security-levels": 6,
    "inconsistent-parameters": 7,
    "inconsistent-selection-criterion": 8,
    "invalid-data-type": 9,
    "invalid-file-access-method": 10,
    "invalid-file-start-position": 11,
    "invalid-operator-name": 12,
    "invalid-parameter-data-type": 13,
    "invalid-time-stamp": 14,
    "key-generation-error": 15,
    "missing-required-parameter": 16,
    "no-objects-of-specified-type": 17,
    "no-space-for-object": 18,
    "no-space-to-add-list-element": 19,
    "no-space-to-write-property": 20,
    "no-vt-sessions-available": 21,
    "property-is-not-a-list": 22,
    "object-deletion-not-permitted": 23,
    "object-identifier-already-exists": 24,
    "operational-problem": 25,
    "password-failure": 26,
    "read-access-denied": 27,
    "security-not-supported": 28,
    "service-request-denied": 29,
    "timeout": 30,
    "unknown-object": 31,
    "unknown-property": 32,
    "reserved1": 33,
    "unknown-vt-class": 34,
    "unknown-vt-session": 35,
    "unsupported-object-type": 36,
    "value-out-of-range": 37,
    "vt-session-already-closed": 38,
    "vt-session-termination-failure": 39,
    "write-access-denied": 40,
    "character-set-not-supported": 41,
    "invalid-array-index": 42,
    "cov-subscription-failed": 43,
    "not-cov-property": 44,
    "optional-functionality-not-supported": 45,
    "invalid-configuration-data": 46,
    "datatype-not-supported": 47,
    "duplicate-name": 48,
    "duplicate-object-id": 49,
    "property-is-not-an-array": 50,
    "abort-buffer-overflow": 51,
    "abort-invalid-apdu-in-this-state": 52,
    "abort-preempted-by-higher-priority-task": 53,
    "abort-segmentation-not-supported": 54,
    "abort-proprietary": 55,
    "abort-other": 56,
    "invalid-tag": 57,
    "network-down": 58,
    "reject-buffer-overflow": 59,
    "reject-inconsistent-parameters": 60,
    "reject-invalid-parameter-data-type": 61,
    "reject-invalid-tag": 62,
    "reject-missing-required-parameter": 63,
    "reject-parameter-out-of-range": 64,
    "reject-too-many-arguments": 65,
    "reject-undefined-enumeration": 66,
    "reject-unrecognized-service": 67,
    "reject-proprietary": 68,
    "reject-other": 69,
    "unknown-device": 70,
    "unknown-route": 71,
    "value-not-initialized": 72,
    "invalid-event-state": 73,
    "no-alarm-configured": 74,
    "log-buffer-full": 75,
    "logged-value-purged": 76,
    "no-property-specified": 77,
    "not-configured-for-triggered-logging": 78,
    "unknown-subscription": 79,
    "parameter-out-of-range": 80,
    "list-element-not-found": 81,
    "busy": 82,
    "communication-disabled": 83,
    "success": 84,
    "access-denied": 85,
    "bad-destination-address": 86,
    "bad-destination-device-id": 87,
    "bad-signature": 88,
    "bad-source-address": 89,
    "bad-timestamp": 90,
    "cannot-use-key": 91,
    "cannot-verify-message-id": 92,
    "correct-key-revision": 93,
    "destination-device-id-required": 94,
    "duplicate-message": 95,
    "encryption-not-configured": 96,
    "encryption-required": 97,
    "incorrect-key": 98,
    "invalid-key-data": 99,
    "key-update-in-progress": 100,
    "malformed-message": 101,
    "not-key-server": 102,
    "security-not-configured": 103,
    "source-security-required": 104,
    "too-many-keys": 105,
    "unknown-authentication-type": 106,
    "unknown-key": 107,
    "unknown-key-revision": 108,
    "unknown-source-message": 109,
    "not-router-to-dnet": 110,
    "router-busy": 111,
    "unknown-network-message": 112,
    "message-too-long": 113,
    "security-error": 114,
    "addressing-error": 115,
    "write-bdt-failed": 116,
    "read-bdt-failed": 117,
    "register-foreign-device-failed": 118,
    "read-fdt-failed": 119,
    "delete-fdt-entry-failed": 120,
    "distribute-broadcast-failed": 121,
    "unknown-file-size": 122,
    "abort-apdu-too-long": 123,
    "abort-application-exceeded-reply-time": 124,
    "abort-out-of-resources": 125,
    "abort-tsm-timeout": 126,
    "abort-window-size-out-of-range": 127,
    "file-full": 128,
    "inconsistent-configuration": 129,
    "inconsistent-object-type": 130,
    "internal-error": 131,
    "not-configured": 132,
    "out-of-memory": 133,
    "value-too-long": 134,
    "abort-insufficient-security": 135,
    "abort-security-error": 136,
    "duplicate-entry": 137,
    "invalid-value-in-this-state": 138,
    "invalid-operation-in-this-state": 139,
    "list-item-not-numbered": 140,
    "list-item-not-timestamped": 141,
    "invalid-data-encoding": 142,
    "bvlc-function-unknown": 143,
    "bvlc-proprietary-function-unknown": 144,
    "header-encoding-error": 145,
    "header-not-understood": 146,
    "message-incomplete": 147,
    "not-a-bacnet-sc-hub": 148,
    "payload-expected": 149,
    "unexpected-data": 150,
    "node-duplicate-vmac": 151,
    "http-unexpected-response-code": 152,
    "http-no-upgrade": 153,
    "http-resource-not-local": 154,
    "http-proxy-authentication-failed": 155,
    "http-response-timeout": 156,
    "http-response-syntax-error": 157,
    "http-response-value-error": 158,
    "http-response-missing-header": 159,
    "http-websocket-header-error": 160,
    "http-upgrade-required": 161,
    "http-upgrade-error": 162,
    "http-temporary-unavailable": 163,
    "http-not-a-server": 164,
    "http-error": 165,
    "websocket-scheme-not-supported": 166,
    "websocket-unknown-control-message": 167,
    "websocket-close-error": 168,
    "websocket-closed-by-peer": 169,
    "websocket-endpoint-leaves": 170,
    "websocket-protocol-error": 171,
    "websocket-data-not-accepted": 172,
    "websocket-closed-abnormally": 173,
    "websocket-data-inconsistent": 174,
    "websocket-data-against-policy": 175,
    "websocket-frame-too-long": 176,
    "websocket-extension-missing": 177,
    "websocket-request-unavailable": 178,
    "websocket-error": 179,
    "tls-client-certificate-error": 180,
    "tls-server-certificate-error": 181,
    "tls-client-authentication-failed": 182,
    "tls-server-authentication-failed": 183,
    "tls-client-certificate-expired": 184,
    "tls-server-certificate-expired": 185,
    "tls-client-certificate-revoked": 186,
    "tls-server-certificate-revoked": 187,
    "tls-error": 188,
    "dns-unavailable": 189,
    "dns-name-resolution-failed": 190,
    "dns-resolver-failure": 191,
    "dns-error": 192,
    "tcp-connect-timeout": 193,
    "tcp-connection-refused": 194,
    "tcp-closed-by-local": 195,
    "tcp-closed-other": 196,
    "tcp-error": 197,
    "ip-address-not-reachable": 198,
    "ip-error": 199,
    "certificate-expired": 200,
    "certificate-invalid": 201,
    "certificate-malformed": 202,
    "certificate-revoked": 203,
    "unknown-security-key": 204,
    "referenced-port-in-error": 205,
    "not-enabled": 206,
    "adjust-scope-required": 207,
    "auth-scope-required": 208,
    "bind-scope-required": 209,
    "config-scope-required": 210,
    "control-scope-required": 211,
    "extended-scope-required": 212,
    "incorrect-client": 213,
    "install-scope-required": 214,
    "insufficient-scope": 215,
    "no-default-scope": 216,
    "no-policy": 217,
    "revoked-token": 218,
    "override-scope-required": 219,
    "inactive-token": 220,
    "unknown-audience": 221,
    "unknown-client": 222,
    "unknown-scope": 223,
    "view-scope-required": 224,
    "incorrect-audience": 225,
    "incorrect-client-origin": 226,
    "invalid-array-size": 227,
    "incorrect-issuer": 228,
    "invalid-token": 229,
}


# BACnetSegmentation
SEGMENTATION: dict[str, int] = {
    "segmented-both": 0,
    "segmented-transmit": 1,
    "segmented-receive": 2,
    "no-segmentation": 3,
}


# BACnetEventState
EVENT_STATES: dict[str, int] = {
    "normal": 0,
    "fault": 1,
    "offnormal": 2,
    "high-limit": 3,
    "low-limit": 4,
    "life-safety-alarm": 5,
}


# BACnetReliability
RELIABILITY: dict[str, int] = {
    "no-fault-detected": 0,
    "no-sensor": 1,
    "over-range": 2,
    "under-range": 3,
    "open-loop": 4,
    "shorted-loop": 5,
    "no-output": 6,
    "unreliable-other": 7,
    "process-error": 8,
    "mult-state-fault": 9,
    "configuration-error": 10,
    "reserved-11": 11,
    "communication-failure": 12,
    "member-fault": 13,
    "monitored-object-fault": 14,
    "tripped": 15,
    "lamp-failure": 16,
    "activation-failure": 17,
    "renew-dhcp-failure": 18,
    "renew-fd-registration-failure": 19,
    "restart-auto-negotiation-failure": 20,
    "restart-failure": 21,
    "proprietary-command-failure": 22,
    "faults-listed": 23,
    "referenced-object-fault": 24,
    "multi-state-out-of-range": 25,
}


# BACnetDeviceStatus
DEVICE_STATUS: dict[str, int] = {
    "operational": 0,
    "operational-read-only": 1,
    "download-required": 2,
    "download-in-progress": 3,
    "non-operational": 4,
    "backup-in-progress": 5,
}


# BACnetPolarity
POLARITY: dict[str, int] = {
    "normal": 0,
    "reverse": 1,
}


# BACnetBinaryPV
BINARY_PV: dict[str, int] = {
    "inactive": 0,
    "active": 1,
}


# BACnetConfirmedServiceChoice
CONFIRMED_SERVICES: dict[str, int] = {
    "acknowledge-alarm": 0,
    "confirmed-cov-notification": 1,
    "confirmed-event-notification": 2,
    "get-alarm-summary": 3,
    "get-enrollment-summary": 4,
    "subscribe-cov": 5,
    "atomic-read-file": 6,
    "atomic-write-file": 7,
    "add-list-element": 8,
    "remove-list-element": 9,
    "create-object": 10,
    "delete-object": 11,
    "read-property": 12,
    "read-property-conditional": 13,
    "read-property-multiple": 14,
    "write-property": 15,
    "write-property-multiple": 16,
    "device-communication-control": 17,
    "confirmed-private-transfer": 18,
    "confirmed-text-message": 19,
    "reinitialize-device": 20,
    "vt-open": 21,
    "vt-close": 22,
    "vt-data": 23,
    "authenticate": 24,
    "request-key": 25,
    "read-range": 26,
    "life-safety-operation": 27,
    "subscribe-cov-property": 28,
    "get-event-information": 29,
    "subscribe-cov-property-multiple": 30,
    "confirmed-cov-notification-multiple": 31,
    "confirmed-audit-notification": 32,
    "audit-log-query": 33,
    "auth-request": 34,
}


# BACnetUnconfirmedServiceChoice
UNCONFIRMED_SERVICES: dict[str, int] = {
    "i-am": 0,
    "i-have": 1,
    "unconfirmed-cov-notification": 2,
    "unconfirmed-event-notification": 3,
    "unconfirmed-private-transfer": 4,
    "unconfirmed-text-message": 5,
    "time-synchronization": 6,
    "who-has": 7,
    "who-is": 8,
    "utc-time-synchronization": 9,
    "write-group": 10,
    "unconfirmed-cov-notification-multiple": 11,
    "unconfirmed-audit-notification": 12,
    "who-am-i": 13,
    "you-are": 14,
}


# --- reject / abort reasons (ASHRAE 135 clause 18.8 / 18.9, hyphenated names) --------

REJECT_REASONS: dict[str, int] = {
    "other": 0,
    "buffer-overflow": 1,
    "inconsistent-parameters": 2,
    "invalid-parameter-data-type": 3,
    "invalid-tag": 4,
    "missing-required-parameter": 5,
    "parameter-out-of-range": 6,
    "too-many-arguments": 7,
    "undefined-enumeration": 8,
    "unrecognized-service": 9,
    "invalid-data-encoding": 10,
}

ABORT_REASONS: dict[str, int] = {
    "other": 0,
    "buffer-overflow": 1,
    "invalid-apdu-in-this-state": 2,
    "preempted-by-higher-priority-task": 3,
    "segmentation-not-supported": 4,
    "security-error": 5,
    "insufficient-security": 6,
    "window-size-out-of-range": 7,
    "application-exceeded-reply-time": 8,
    "out-of-resources": 9,
    "tsm-timeout": 10,
    "apdu-too-long": 11,
}

# --- frequently used numbers ---------------------------------------------------------

OBJECT_ANALOG_INPUT = 0
OBJECT_ANALOG_OUTPUT = 1
OBJECT_ANALOG_VALUE = 2
OBJECT_BINARY_INPUT = 3
OBJECT_BINARY_OUTPUT = 4
OBJECT_BINARY_VALUE = 5
OBJECT_DEVICE = 8
OBJECT_MULTI_STATE_INPUT = 13
OBJECT_MULTI_STATE_OUTPUT = 14
OBJECT_MULTI_STATE_VALUE = 19
OBJECT_NETWORK_PORT = 56
OBJECT_PROPRIETARY_MIN = 128
MAX_OBJECT_TYPE = 1023
MAX_INSTANCE = 4194303  # 0x3FFFFF; 4194303 is the "unconfigured" wildcard
MAX_PROPERTY_ID = 4194303

PROP_ACTIVE_TEXT = 4
PROP_ALL = 8
PROP_COV_INCREMENT = 22
PROP_DESCRIPTION = 28
PROP_EVENT_STATE = 36
PROP_INACTIVE_TEXT = 46
PROP_LOCATION = 58
PROP_NUMBER_OF_STATES = 74
PROP_OBJECT_IDENTIFIER = 75
PROP_OBJECT_LIST = 76
PROP_OBJECT_NAME = 77
PROP_OBJECT_TYPE = 79
PROP_OUT_OF_SERVICE = 81
PROP_POLARITY = 84
PROP_PRESENT_VALUE = 85
PROP_PRIORITY_ARRAY = 87
PROP_RELIABILITY = 103
PROP_RELINQUISH_DEFAULT = 104
PROP_STATE_TEXT = 110
PROP_STATUS_FLAGS = 111
PROP_UNITS = 117
PROP_PROPERTY_LIST = 371

SERVICE_CONFIRMED_SUBSCRIBE_COV = 5
SERVICE_CONFIRMED_READ_PROPERTY = 12
SERVICE_CONFIRMED_READ_PROP_MULTIPLE = 14
SERVICE_CONFIRMED_WRITE_PROPERTY = 15
SERVICE_CONFIRMED_WRITE_PROP_MULTIPLE = 16

SERVICE_UNCONFIRMED_I_AM = 0
SERVICE_UNCONFIRMED_I_HAVE = 1
SERVICE_UNCONFIRMED_COV_NOTIFICATION = 2
SERVICE_UNCONFIRMED_WHO_HAS = 7
SERVICE_UNCONFIRMED_WHO_IS = 8

ERROR_CLASS_DEVICE = 0
ERROR_CLASS_OBJECT = 1
ERROR_CLASS_PROPERTY = 2
ERROR_CLASS_RESOURCES = 3
ERROR_CLASS_SECURITY = 4
ERROR_CLASS_SERVICES = 5

ERROR_CODE_OTHER = 0
ERROR_CODE_INVALID_DATA_TYPE = 9
ERROR_CODE_UNKNOWN_OBJECT = 31
ERROR_CODE_UNKNOWN_PROPERTY = 32
ERROR_CODE_VALUE_OUT_OF_RANGE = 37
ERROR_CODE_WRITE_ACCESS_DENIED = 40
ERROR_CODE_INVALID_ARRAY_INDEX = 42
ERROR_CODE_PROPERTY_IS_NOT_AN_ARRAY = 50

SEGMENTATION_BOTH = 0
SEGMENTATION_TRANSMIT = 1
SEGMENTATION_RECEIVE = 2
SEGMENTATION_NONE = 3

# Common abbreviations accepted by object_type_number() (not BACnet names).
OBJECT_TYPE_ABBREVIATIONS: dict[str, str] = {
    "ai": "analog-input",
    "ao": "analog-output",
    "av": "analog-value",
    "bi": "binary-input",
    "bo": "binary-output",
    "bv": "binary-value",
    "msi": "multi-state-input",
    "mso": "multi-state-output",
    "msv": "multi-state-value",
    "dev": "device",
    "iv": "integer-value",
    "piv": "positive-integer-value",
    "lav": "large-analog-value",
    "csv": "characterstring-value",
    "np": "network-port",
    "nc": "notification-class",
    "tl": "trend-log",
}


# --- reverse tables ---------------------------------------------------------------------


def _reverse(table: dict[str, int]) -> dict[int, str]:
    return {v: k for k, v in table.items()}


OBJECT_TYPE_NAMES: dict[int, str] = _reverse(OBJECT_TYPES)
PROPERTY_NAMES: dict[int, str] = _reverse(PROPERTIES)
UNIT_NAMES: dict[int, str] = _reverse(UNITS)
ERROR_CLASS_NAMES: dict[int, str] = _reverse(ERROR_CLASSES)
ERROR_CODE_NAMES: dict[int, str] = _reverse(ERROR_CODES)
REJECT_REASON_NAMES: dict[int, str] = _reverse(REJECT_REASONS)
ABORT_REASON_NAMES: dict[int, str] = _reverse(ABORT_REASONS)
SEGMENTATION_NAMES: dict[int, str] = _reverse(SEGMENTATION)
CONFIRMED_SERVICE_NAMES: dict[int, str] = _reverse(CONFIRMED_SERVICES)
UNCONFIRMED_SERVICE_NAMES: dict[int, str] = _reverse(UNCONFIRMED_SERVICES)

# case-insensitive lookup tables
_OBJECT_TYPES_CI = {k.lower(): v for k, v in OBJECT_TYPES.items()}
_PROPERTIES_CI = {k.lower(): v for k, v in PROPERTIES.items()}
_UNITS_CI = {k.lower(): v for k, v in UNITS.items()}


# --- helpers ------------------------------------------------------------------------------


def _norm(name: str) -> str:
    return name.strip().lower().replace("_", "-").replace(" ", "-")


def _lookup(value: str | int, table: dict[str, int], what: str, limit: int) -> int:
    if isinstance(value, bool):
        raise ValueError(f"invalid BACnet {what}: {value!r}")
    if isinstance(value, int):
        number = value
    elif isinstance(value, str):
        text = value.strip()
        if text.isdigit():
            number = int(text)
        else:
            try:
                return table[_norm(text)]
            except KeyError:
                raise ValueError(f"unknown BACnet {what}: {value!r}") from None
    else:
        raise ValueError(f"invalid BACnet {what}: {value!r}")
    if not 0 <= number <= limit:
        raise ValueError(f"BACnet {what} out of range: {number}")
    return number


def object_type_number(value: str | int) -> int:
    """Object type number of a name (``"analog-input"``, ``"analog_input"``,
    ``"AI"``), a decimal string or an int. Raises :class:`ValueError`."""
    if isinstance(value, str):
        abbr = OBJECT_TYPE_ABBREVIATIONS.get(value.strip().lower())
        if abbr is not None:
            return OBJECT_TYPES[abbr]
    return _lookup(value, _OBJECT_TYPES_CI, "object type", MAX_OBJECT_TYPE)


def property_number(value: str | int) -> int:
    """Property identifier of a name (``"present-value"``, ``"present_value"``),
    a decimal string or an int. Raises :class:`ValueError`."""
    return _lookup(value, _PROPERTIES_CI, "property", MAX_PROPERTY_ID)


def unit_number(value: str | int) -> int:
    """Engineering unit number of a name (``"degrees-celsius"``), a decimal
    string or an int. Raises :class:`ValueError`."""
    return _lookup(value, _UNITS_CI, "engineering unit", 0xFFFF)


def object_type_name(number: int) -> str:
    """BACnet stack text name of an object type, the decimal number if unknown."""
    return OBJECT_TYPE_NAMES.get(number, str(number))


def property_name(number: int) -> str:
    """BACnet stack text name of a property, the decimal number if unknown."""
    return PROPERTY_NAMES.get(number, str(number))


def unit_name(number: int) -> str:
    """BACnet stack text name of an engineering unit, the decimal number if unknown."""
    return UNIT_NAMES.get(number, str(number))


def error_class_name(number: int) -> str:
    return ERROR_CLASS_NAMES.get(number, str(number))


def error_code_name(number: int) -> str:
    return ERROR_CODE_NAMES.get(number, str(number))


def reject_reason_name(number: int) -> str:
    if number >= 64:
        return f"proprietary-{number}"
    return REJECT_REASON_NAMES.get(number, str(number))


def abort_reason_name(number: int) -> str:
    if number >= 64:
        return f"proprietary-{number}"
    return ABORT_REASON_NAMES.get(number, str(number))


def segmentation_name(number: int) -> str:
    return SEGMENTATION_NAMES.get(number, str(number))


def parse_object_ref(ref: str | tuple[str | int, int]) -> tuple[int, int]:
    """Parse an object reference into ``(type, instance)``.

    Accepts ``"analog-input:1"``, ``"analog-input,1"``, ``"analog-input 1"``,
    ``"AI:1"``, ``"0:1"`` or an existing ``(type, instance)`` pair.
    Raises :class:`ValueError`.
    """
    if isinstance(ref, tuple | list):
        if len(ref) != 2:
            raise ValueError(f"invalid object reference: {ref!r}")
        obj_type, instance = ref
        inst = int(instance)
    else:
        text = str(ref).strip()
        for sep in (":", ",", " ", "/"):
            if sep in text:
                obj_type, _, inst_text = text.rpartition(sep)
                break
        else:
            raise ValueError(f"invalid object reference (expected '<type>:<instance>'): {ref!r}")
        try:
            inst = int(inst_text.strip())
        except ValueError:
            raise ValueError(f"invalid object instance in {ref!r}") from None
    if not 0 <= inst <= MAX_INSTANCE:
        raise ValueError(f"object instance out of range in {ref!r}")
    return object_type_number(obj_type), inst


def format_object_ref(obj_type: str | int, instance: int) -> str:
    """``"analog-input:1"`` for ``(0, 1)``."""
    return f"{object_type_name(object_type_number(obj_type))}:{int(instance)}"
