# SPDX-License-Identifier: Apache-2.0
# native_sim (64-bit host build): networking through the host's sockets
# (Native Simulator Offloaded Sockets), storage in the flash simulator
# (backed by flash.bin, see --flash=<file>).
CONFIG_NET_DRIVERS=y
CONFIG_NET_SOCKETS_OFFLOAD=y
CONFIG_NET_NATIVE_OFFLOADED_SOCKETS=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
# NSOS uses AF_UNIX-sized socket addresses (110 bytes)
CONFIG_MCUMGR_TRANSPORT_NETBUF_USER_DATA_SIZE=112
